import PopIn from "@/components/motion/PopIn";
import DropIn from "@/components/motion/DropIn";
import Cta from "@/components/ui/CTA";
import GeometricIcon from "@/components/ui/icons";
import StatCounter from "./StatCounter";
import { SITE_PHONE_HREF } from "@/lib/constants";

/* Sticker for each speech-bubble shape below — a small geometric-icon
   badge tucked behind a corner of the shape. On touch devices there's
   no hover to trigger a reveal, so below `sm` it just sits visible at
   rest (sized down to match the smaller mobile type), showing off the
   same tilt/color as a permanent little accent. From `sm` up (where a
   mouse is more likely) it's hidden at rest (scale-0 + rotated +
   invisible) and pops out on hover via plain CSS `group-hover` (no JS
   needed, and it composes fine with DropIn's GSAP entrance since that
   only ever touches `transform` inline, then clears it — see DropIn's
   own comment).
   Kept out of the tab order / a11y tree since it's decorative. */
function HoverSticker({
  index,
  className,
}: {
  index: number;
  /** Full literal Tailwind classes for this instance — position,
   *  bg color, rest rotation AND the `group-hover:rotate-[...]`
   *  variant, all written out in full at the call site. Utility
   *  classes built by string-concatenating a prefix onto a prop
   *  (e.g. `group-hover:${rotateVar}`) never get generated by
   *  Tailwind's static scan, so every variant has to appear intact
   *  in the source — hence one big literal string per usage instead
   *  of separate position/rotate props. */
  className: string;
}) {
  return (
    <div
      aria-hidden="true"
      className={`pointer-events-none absolute z-0 flex h-10 w-10 scale-100 items-center justify-center rounded-full opacity-100 shadow-lg ring-2 ring-white/15 transition-all duration-500 ease-[cubic-bezier(0.34,1.56,0.64,1)] sm:h-16 sm:w-16 sm:scale-0 sm:opacity-0 sm:group-hover:scale-100 sm:group-hover:opacity-100 ${className}`}
    >
      <GeometricIcon
        index={index}
        className="h-5 w-5 text-white sm:h-7 sm:w-7"
      />
    </div>
  );
}

const STATS = [
  {
    value: "1.37M",
    label: "Employer Businesses In Canada",
  },
  {
    value: "$21.1B",
    label: "Canadian Digital Advertising Market",
  },
  {
    value: "+16%",
    label: "Digital Ad Market Growth In 2025",
  },
  {
    value: "#1",
    label: "Search Remains Canada\u2019s Largest Digital Ad Category",
  },
];

export default function ServicesMarketStats() {
  return (
    <section className="bg-[#0E0F11]">
      <div className="container-x w-full bg-[#0E0F11] pt-10 pb-12 sm:pt-12 sm:pb-14 md:pt-14 md:pb-16 lg:pt-16">
        <div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between lg:gap-10">
          <div className="flex items-center gap-2 lg:shrink-0 lg:pt-2">
            <span className="font-mono text-xs font-medium tracking-[0.16em] whitespace-nowrap text-white uppercase sm:text-sm">
              [ ] Canadian Businesses
            </span>
          </div>

          <h2 className="indent-8 text-left text-[24px] leading-[1.25] font-medium tracking-heading text-white sm:indent-10 sm:text-[32px] md:indent-12 md:text-[40px] lg:w-[680px] lg:shrink-0 xl:text-[44px]">
            Canadian Businesses Are Competing In A Digital-First Market
          </h2>
        </div>
      </div>

      <div className="bg-[#0E0F11]">
        <div className="container-x w-full">
          {STATS.map((stat, i) => (
            <div key={stat.label}>
              {i > 0 && (
                <div
                  aria-hidden="true"
                  className="h-[0.5px] w-full bg-white/15"
                />
              )}

              <div className="flex flex-col gap-4 py-10 sm:grid sm:grid-cols-[80px_1fr_auto] sm:items-center sm:gap-8 sm:py-14 md:gap-14 md:py-16 lg:gap-20">
                <span className="font-mono text-xs tracking-[0.14em] text-white/40 uppercase">
                  {`S . 00${i + 1}`}
                </span>

                <StatCounter
                  value={stat.value}
                  className="text-[44px] leading-none font-medium tracking-tight text-white sm:text-[56px] md:text-[64px] lg:text-[72px]"
                />

                <p className="max-w-56 text-base leading-snug font-normal tracking-tight text-white uppercase sm:text-lg md:text-xl">
                  {stat.label}
                </p>
              </div>
            </div>
          ))}

          <div aria-hidden="true" className="h-[0.5px] w-full bg-white/15" />
        </div>
      </div>

      <div className="container-x w-full">
        {/* ==========================================================
            SPEECH-BUBBLE STACK — replaces the old image+text pairs.
            Three shapes matching the reference mock: rounded purple
            box, pink pill/blob, tilted purple box. Each one drops +
            tilts into place on scroll via DropIn (see that file for
            why this is a one-shot GSAP settle, not a live physics
            sim) — it falls in, overshoots slightly, and stays put;
            it never keeps moving after landing. Resting tilt (the
            3rd box's -rotate-3) lives as a plain Tailwind class on
            the same element DropIn wraps, so it's still there once
            DropIn's clearProps hands the transform back to CSS.
            Staggered via each DropIn's own `delay` so they read as
            falling one after another rather than all at once.
            ========================================================== */}
        <div className="mt-14 flex flex-col items-center gap-8 sm:mt-16 sm:gap-10 md:mt-20 md:gap-12">
          <div className="group relative w-full">
            <HoverSticker
              index={4}
              className="-top-5 -right-4 -rotate-12 bg-[#FE96C9] group-hover:rotate-[10deg] sm:-top-6 sm:-right-6"
            />
            <DropIn
              className="relative z-10 w-full rounded-[32px] bg-[#8B5CF6] px-8 py-10 sm:px-12 sm:py-12"
              fromY={-70}
              fromRotate={-14}
              delay={0}
            >
              <p className="text-center text-balance text-[18px] leading-[1.35] font-normal normal-case tracking-tight text-black-text sm:text-[24px] md:text-[30px] lg:text-[34px]">
                A website and a few social media accounts can give your business
                an online presence, but that doesn&rsquo;t automatically bring
                in customers, especially in a competitive market like Vancouver.
              </p>
            </DropIn>
          </div>

          <div className="group relative w-full">
            <HoverSticker
              index={13}
              className="-bottom-5 -left-4 rotate-6 bg-[#8B5CF6] group-hover:-rotate-[8deg] sm:-bottom-6 sm:-left-6"
            />
            <DropIn
              className="relative z-10 w-full rounded-[999px] bg-[#FE96C9] px-10 py-12 sm:px-14 sm:py-14"
              fromY={-70}
              fromRotate={12}
              delay={0.12}
            >
              <p className="text-center text-balance text-[18px] leading-[1.35] font-normal normal-case tracking-tight text-black-text sm:text-[24px] md:text-[30px] lg:text-[34px]">
                That&rsquo;s where the digital marketers at{" "}
                <PopIn className="inline-block -rotate-2 rounded-md bg-[#8B5CF6] px-3 py-1 text-white-primary">
                  Technico
                </PopIn>{" "}
                Digital Solutions come in. We look at how customers find your
                business, what happens when they reach your website, and where
                potential leads drop off.
              </p>
            </DropIn>
          </div>

          <div className="group relative w-full">
            <HoverSticker
              index={21}
              className="-top-5 -right-4 rotate-3 bg-[#FE96C9] group-hover:rotate-[-14deg] sm:-top-6 sm:-right-6"
            />
            <DropIn
              className="relative z-10 -rotate-3 w-full rounded-[30px] bg-[#8B5CF6] px-8 py-10 sm:px-12 sm:py-12"
              fromY={-70}
              fromRotate={-16}
              delay={0.24}
            >
              <p className="text-center text-balance text-[18px] leading-[1.35] font-normal normal-case tracking-tight text-black-text sm:text-[24px] md:text-[30px] lg:text-[34px]">
                SEO, paid ads, content, and social media are then brought
                together to help local businesses like yours generate qualified
                leads, ecommerce stores attract more customers, and growing
                brands reach a wider audience across Canada.
              </p>
            </DropIn>
          </div>
        </div>
      </div>

      <Cta
        title="We go the extra mile to help you"
        description="Fulfill your business plans with targeted digital marketing strategies. Partner with us today and see competitive results."
        cta={{ label: "Book A Call", href: SITE_PHONE_HREF }}
      />
    </section>
  );
}
